

jobs:
  - job:
    pool:
      vmImage: ubuntu-latest
    variables:
      a: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 100)]
      b: $[pipeline.startTime]
    steps:
    - bash: echo $(a)
    - bash: echo $(b)



######################################################
# Public correctness jobs
######################################################
