

jobs:
  - job:
    pool:
      vmImage: ubuntu-latest
    variables:
      a: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 100)]
      b: $[eq(mod(format('{0:d', pipeline.startTime), 3), 0)]
    steps:
    - bash: echo $(a)
    - bash: echo $(b)



######################################################
# Public correctness jobs
######################################################
