

jobs:
  - job:
    pool:
      vmImage: ubuntu-latest
    variables:
      a: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 100)]
      b: $[format('{0:d}', pipeline.startTime)]
    steps:
    - pwsh: echo "##vso[task.setvariable variable=day]([datetime]'$(b)').DayOfWeek"

    - bash: echo $(b)
    - bash: echo $(day)



######################################################
# Public correctness jobs
######################################################
