

jobs:
  - job:
    pool:
      vmImage: ubuntu-latest
    variables:
      - name: startTime
        value: $[pipeline.startTime]
    steps:
    - pwsh: echo "##vso[task.setvariable variable=day]$(([datetime]'$(startTime)').DayOfWeek)"
    - bash: echo $(day)
    - template: test.yml
      parameters:
        day: $(day)



######################################################
# Public correctness jobs
######################################################
