pool: ubuntu-latest

variables:
- name: startTime
  value: $[pipeline.startTime]

jobs:
  - job: getday
    steps:
      - bash: echo $STARTTIME
      - pwsh: gci env:\ | % { echo $_.Name } 
      - pwsh: echo "##vso[task.setvariable variable=day;isOutput=true]$(([datetime]$env:STARTTIME).DayOfWeek)"
        name: getday
      - pwsh: echo $(getday.day)
        name: echoDay
        
  - job: dowork
    dependsOn: getday
    variables:
      dayOfWeek: $[ dependencies.getday.outputs['getday.day'] ]
    steps:
    - bash: echo it's one of our days!
      # condition: or(eq(dependencies.getday.outputs['getday.day'], 'Monday'), eq(dependencies.getday.outputs['getday.day'], 'Thursday'))
      condition: or(eq(variables['dayOfWeek'], 'Monday'), eq(variables['dayOfWeek'], 'Thursday'))
    - bash: echo "nah it's sunday"
      condition: eq(variables['dayOfWeek'], 'Sunday')


######################################################
# Public correctness jobs
######################################################
