

jobs:
  - job:
    pool:
      vmImage: ubuntu-latest
    variables:
      b: $[format('{0}', pipeline.startTime)]
    steps:
    - pwsh: echo "##vso[task.setvariable variable=day]$(([datetime]'$(b)').DayOfWeek)"
    - bash: echo $(day)
    - ${{ if eq($(day), 'Saturday') }}:
      - bash: echo "it's saturday"
    - ${{ if ne($(day), 'Saturday') }}:
      - bash: echo "Not saturday"



######################################################
# Public correctness jobs
######################################################
