

jobs:
  - job:
    pool:
      vmImage: ubuntu-latest
    variables:
      - name: startTime
        value: $[pipeline.startTime]
    steps:
    - pwsh: echo "##vso[task.setvariable variable=day]$(([datetime]'$(startTime)').DayOfWeek)"
    - bash: echo $(day)
    - ${{ if eq(variables['day'], 'Saturday') }}:
      - bash: echo "it's saturday"
    - ${{ if eq(variables['day'], 'Monday') }}:
      - bash: echo "it's monday"



######################################################
# Public correctness jobs
######################################################
