pool:
  vmImage: ubuntu-latest

variables:
- name: startTime
  value: $[format("{0}", pipeline.startTime)]

jobs:
  - job: getday
    steps:
      - bash: echo $STARTTIME
      - bash: echo $[pipeline.startTime]
      - pwsh: gci env:\ | % { echo $_.Name }
      - pwsh: echo "##vso[task.setvariable variable=day]$(([datetime] $(startTime) ).DayOfWeek)"
        name: getday
        
  - job: dowork
    dependsOn: getday
    steps:
    - bash: echo day is '$(day)'
    - bash: echo $(day) is one of our days
      condition: and(succeeded(), or(eq(dependencies.getday.outputs['getday.day'], 'Monday'), eq(dependencies.getday.outputs['getday.day'], 'Thursday')))
    - bash: echo nah it's saturday
      condition: and(succeeded(), eq(dependencies.getday.outputs['getday.day'], 'Saturday'))


######################################################
# Public correctness jobs
######################################################
